### PR TITLE
Updated the readme for people landing here cold

### PR DESCRIPTION
**Pull request by tonyyates**
The purpose here is to ensure people are clear with commit messages and inform
others how they can contribute if they don't understand git/github which will
be the vast majority of the user base.

### CODE REVIEW

**Comment by tonyyates** [comment]
Another for a quick review for typo's please @mattstibbs

**Comment by mattstibbs** [comment]
I removed the license part previously as technically this needs to be licensed under Creative Commons as it is not code. Suggest remove that and we add a Creative Commons license file.

**Comment by tonyyates** [comment]
Ok agree with that

**Comment by mattstibbs** [comment]
@tonyyates If you amend your commit I'll merge

**Comment by mattstibbs** [comment]
@tonyyates I realised I could do it :)

**Pull request merged**
